//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace requiredSerivices1.RequiredServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequiredServiceReference.ReqIService")]
    public interface ReqIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReqIService/WebDownload", ReplyAction="http://tempuri.org/ReqIService/WebDownloadResponse")]
        string WebDownload(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReqIService/WebDownload", ReplyAction="http://tempuri.org/ReqIService/WebDownloadResponse")]
        System.Threading.Tasks.Task<string> WebDownloadAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReqIService/WordsFilter", ReplyAction="http://tempuri.org/ReqIService/WordsFilterResponse")]
        string WordsFilter(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReqIService/WordsFilter", ReplyAction="http://tempuri.org/ReqIService/WordsFilterResponse")]
        System.Threading.Tasks.Task<string> WordsFilterAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReqIServiceChannel : requiredSerivices1.RequiredServiceReference.ReqIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReqIServiceClient : System.ServiceModel.ClientBase<requiredSerivices1.RequiredServiceReference.ReqIService>, requiredSerivices1.RequiredServiceReference.ReqIService {
        
        public ReqIServiceClient() {
        }
        
        public ReqIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReqIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReqIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReqIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WebDownload(string url) {
            return base.Channel.WebDownload(url);
        }
        
        public System.Threading.Tasks.Task<string> WebDownloadAsync(string url) {
            return base.Channel.WebDownloadAsync(url);
        }
        
        public string WordsFilter(string str) {
            return base.Channel.WordsFilter(str);
        }
        
        public System.Threading.Tasks.Task<string> WordsFilterAsync(string str) {
            return base.Channel.WordsFilterAsync(str);
        }
    }
}
