//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace requiredSerivices1.ElectiveServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ElectiveServiceReference.combelectIService")]
    public interface combelectIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/combelectIService/Weather5day", ReplyAction="http://tempuri.org/combelectIService/Weather5dayResponse")]
        string[] Weather5day(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/combelectIService/Weather5day", ReplyAction="http://tempuri.org/combelectIService/Weather5dayResponse")]
        System.Threading.Tasks.Task<string[]> Weather5dayAsync(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/combelectIService/GetSolarsaving", ReplyAction="http://tempuri.org/combelectIService/GetSolarsavingResponse")]
        string GetSolarsaving(string zipcode, int effitiency, int area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/combelectIService/GetSolarsaving", ReplyAction="http://tempuri.org/combelectIService/GetSolarsavingResponse")]
        System.Threading.Tasks.Task<string> GetSolarsavingAsync(string zipcode, int effitiency, int area);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface combelectIServiceChannel : requiredSerivices1.ElectiveServiceReference.combelectIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class combelectIServiceClient : System.ServiceModel.ClientBase<requiredSerivices1.ElectiveServiceReference.combelectIService>, requiredSerivices1.ElectiveServiceReference.combelectIService {
        
        public combelectIServiceClient() {
        }
        
        public combelectIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public combelectIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public combelectIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public combelectIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Weather5day(string zipcode) {
            return base.Channel.Weather5day(zipcode);
        }
        
        public System.Threading.Tasks.Task<string[]> Weather5dayAsync(string zipcode) {
            return base.Channel.Weather5dayAsync(zipcode);
        }
        
        public string GetSolarsaving(string zipcode, int effitiency, int area) {
            return base.Channel.GetSolarsaving(zipcode, effitiency, area);
        }
        
        public System.Threading.Tasks.Task<string> GetSolarsavingAsync(string zipcode, int effitiency, int area) {
            return base.Channel.GetSolarsavingAsync(zipcode, effitiency, area);
        }
    }
}
